### ISSUE TITLE
Provide method for filtering 'Assign Users' and 'Assign Books' pages by 'Unassigned'

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-multi-institution#104]
As a network manager, I want to quickly see a list of all 'Unassigned' users or books on my network so that I can focus on assigning these books/users to the relevant institution as quickly as possible. 

At present, there is no method provided for me that allows me to filter the list so that only these books/users are shown. All I can do is sort the column so unassigned displays at the top. We support full text search in the Institution field, but searching by 'Unassigned' returns no results because the user/book has a null value for their institution.

There are two ways I can think of that might solve this problem for the user:
1. Allow them to use the existing search feature to filter Unassigned books/users
1. provide some kind of link/filter that lets them show 'Unassigned' books/users only on each page

Full list:
![Screenshot from 2024-03-14 11-15-31](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/1e5e6d56-4b90-4bc2-836f-de6b63185735)
Search by 'Unassigned' (no results):
![Screenshot from 2024-03-14 11-15-12](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/d415cf4b-0df2-40cb-8ab2-5839f0652ea3)
Search by 'Berklee' (returns all users assigned to institutions with Berklee in the title):
![Screenshot from 2024-03-14 11-14-54](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/db5d0660-6ea0-4132-932e-e130038f5d14)

We have agreed on adding a button/link that filters the list only by unassigned. Once applied, the user should be able to clear/remove it, much like they do when they search. Text could read 'Show Unassigned Users Only' or 'Show Unassigned Books Only'

**Comment by richard015ar** [comment]
WIP at https://github.com/pressbooks/pressbooks-multi-institution/pull/109 and in ricardodev for early testing

**Comment by richard015ar** [comment]
Changes ready for review. @tw77 in case you want to proceed with early testing, these changes are available at ricardodev.pressbooks.network. Testing sample case described in: https://github.com/pressbooks/pressbooks-multi-institution/pull/109#issue-2193279826

**Comment by tw77** [comment]
Although this successfully filters books and users on the relevant lists on ricardodev, I notice that there's no visual indication on the filter link itself that I've selected 'Unassigned' rather than 'All' _while_ 'Unassigned' is selected. 

For example, I've actually selected Unassigned in this screenshot and am viewing the Unassigned results:
<img width="173" alt="Screenshot 2024-03-19 at 7 15 27 AM" src="https://github.com/pressbooks/pressbooks-multi-institution/assets/44182629/33b2b80e-f2f1-4852-a7e7-aa93d505c959">

Because the filter persists when navigating to and from the Assign Users or Assign Books pages, the potential for the user being disoriented by this visually unchanged linked text is high.

**Comment by SteelWagstaff** [comment]
Compare with the users.php list -- when active, the link becomes black and bold:
![Screenshot from 2024-03-19 07-25-16](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/e94e1199-5c74-4209-b9d6-e25cc73f9f56)

**Comment by richard015ar** [comment]
yes, It was the last change I made. Good catch. I fixed it.

**Comment by arzola** [comment]
Tested and merged

**Comment by SteelWagstaff** [comment]
When I click unassigned on the "Assign Books' page, I'm actually redirected to the list of unassigned users. The URL points to `https://dev.pressbooks.network/wp/wp-admin/admin.php?page=pb_multi_institutions_users&unassigned=1` instead of `pb_multi_institution_assign_book&unassigned=1`

**Comment by SteelWagstaff** [comment]
We could also standardize the page names if it's not too much trouble? `pb_multi_institutions_users` could become `pb_assign_users` and `pb_multi_institution_assign_book` could become `pb_assign_books`

**Comment by SteelWagstaff** [comment]
Tested and works as expected on dev.pressbooks.network
