### ISSUE TITLE
Fix permissions for Institutional Managers

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks-multi-institution#131]
As an IM I am facing the following problems:

- [x] When deactivating or deleting a book from my institution, the confirmation page loads, but when performing the action I see: "Sorry, you are not allowed to access this page." The book is not deactivated or deleted.
- [x] When deleting a user, the confirmation page loads, but when performing the action I see: "Sorry, you are not allowed to access this page." However, the user _is_ deleted.
- [x] When my institution does not have any books, the user list is always empty, even if my institution contains users. Nevertheless, the user count seems to be correct.

**Comment by arzola** [comment]
PR to fix permissions #133

**Comment by cmurtagh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Q4-2024-65061c7b8bd3139dea5e5373/issues/pressbooks/pressbooks-multi-institution/131?planning-poker) with Zenhub @richard015ar @tw77 @fdalcin @ho-man-chan

**Comment by tw77** [comment]
All three fixes are working as expected on dev / ecotest.
