### ISSUE TITLE
It is possible to add multiple institutions with the same name

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-multi-institution#134]
When I add an institution, the only validation performed on the "Name" field is that it must be filled out. It's possible to add a duplicate institution with the name of an existing institution with no warning or validation error.

**Expected Behaviour**

It should not be possible to add multiple institutions with the same name in a network.

**Comment by richard015ar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Q4-2024-65061c7b8bd3139dea5e5373/issues/pressbooks/pressbooks-multi-institution/134?planning-poker) with Zenhub @fdalcin @ho-man-chan @tw77

**Comment by tw77** [comment]
Fix is working as expected on ecotest.
