### ISSUE TITLE
GitHub Actions can't be run on PRs from a fork as the `composer install` step depends on a secret

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-multi-institution#136]
In the `run-tests.yml` workflow, Composer dependencies are installed with a composer auth token which is stored in the repository's GitHub Actions secrets: https://github.com/greatislander/pressbooks-multi-institution/blob/23115ffad94406bdea63025e42ddf74728a676d0/.github/workflows/run-tests.yml#L66

I'm not sure why this is necessary for this plugin's dependencies. It has the effect of preventing GitHub Actions from running against PRs from open source contributors.

**Comment by SteelWagstaff** [comment]
I think this was a vestige from when this was a private plugin? Thanks for the PR fixing this.
