### ISSUE TITLE
Institutional Managers see 'Sorry, you're not allowed to access this page' errors

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-multi-institution#170]
In our most recent shared network webinar, there were two instances where an institutional manager saw unexpected 'Sorry, you're not allwoed to access this page' errors on the sharedstaging.pressbooks.pub network. The user was `mallen4`

First, they saw an error message when trying to load their user list from the 'View User List' link on their Institutional Manager dashboard (this URL was `https://sharedstaging.pressbooks.pub/wp/wp-admin/network/users.php?page=pb_network_analytics_userlist` as opposed to `https://sharedstaging.pressbooks.pub/wp/wp-admin/users.php?page=pb_network_analytics_userlist` which does work). They were able to recover from this one by clicking the User link from their admin sidebar menu. 

Second, they saw the error when clicking the 'Add Users' button in the top nav bar (`https://sharedstaging.pressbooks.pub/wp/wp-admin/network/users.php?page=user_bulk_new`). They could not access the bulk add new users page, even when removing the network path from the URL. See video recording below:

https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/c53ba8c0-f374-43cb-8351-697d85c89209

In both cases, institutional managers will expect to be access these pages and perform the relevant actions.

**Comment by richard015ar** [comment]
The first bug sounds like an error due to the context where the user is. Sidebar menu takes the user to the root site or network context, making the pages available for both contexts, nonetheless, it seems like for the hooks we put in place (list of allowed pages) maybe the root_site level of the users page is not in the allowed list. For context, I think the users page should work on both contexts for NMs and Super admins.

**Comment by fdalcin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks-multi-institution/170?planning-poker) with Zenhub @arzola @ho-man-chan @richard015ar @tw77

**Comment by cmurtagh** [comment]
We will go over this in bug scrub on Wednesday the 19th.

**Comment by tw77** [comment]
I haven't been able to recreate the first error while following the flow from the video as IM, but I'm seeing the second error when clicking the 'Add Users' button in the top nav bar as an IM, even on University, where I'm taken to https://university.pressbooks.pub/wp/wp-admin/network/users.php?page=user_bulk_new. This will need to be fixed as a permissions issue.

<img width="1440" alt="Screenshot 2024-07-11 at 11 56 12 AM" src="https://github.com/user-attachments/assets/755eac22-27cc-4e87-a998-77537dd132b6">

**Comment by SteelWagstaff** [comment]
@JohnMcLeod13 just showed me that he runs into the bug when trying to launch the user list as an institutional manager on sharedstaging. The dashboard links to `https://sharedstaging.pressbooks.pub/wp/wp-admin/network/users.php?page=pb_network_analytics_userlist` which he does not have permission to view. The left nav menu links to `https://sharedstaging.pressbooks.pub/wp/wp-admin/admin.php?page=pb_network_analytics_userlist` which he does have permission to view

**Comment by tw77** [comment]
That's strange, I just double-checked and for me as an institutional manager on sharedstaging, both the dashboard and left nav menu link to the viewable `https://sharedstaging.pressbooks.pub/wp/wp-admin/network/admin.php?page=pb_network_analytics_userlist` -- I wonder if there's a difference between John and my institutional manager accounts on that network leading this wrong URL to persist for him, some reason the devs might understand.

(Top nav 'Add Users' still leads me to a page I can't view as an institutional manager on sharedstaging, `https://sharedstaging.pressbooks.pub/wp/wp-admin/network/users.php?page=user_bulk_new`)

**Comment by JohnMcLeod13** [comment]
Great question, is there a difference between the accounts john1 and thomtemporarytest? However, the same issue was noted for institutional managers on the [UEN network](uen.pressbooks.pub) where the links (dashboard link to user list and Top nav link 'Add Users') don't work for these institutional manager accounts: 
Misty Allen  mallen4@weber.edu
Michael Whitchurch  michael_whitchurch@byu.edu

**Comment by tw77** [comment]
Now able to reproduce the first error as thomtemporarytest too - I had been using the wrong link when aiming to recreate this error from the dashboard. We'll look for a fix in bug scrub today.

**Comment by tw77** [comment]
@JohnMcLeod13 @SteelWagstaff Fixes for both errors here are now released to production networks as well as https://sharedstaging.pressbooks.pub/
