### ISSUE TITLE
Remove 'Institutions' from left sidebar of book dashboard

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-multi-institution#198]
The 'Institutions' item is being unintentionally displayed to super admins and network managers in the left sidebar menu of all book dashboards. This menu item should only be displayed at the network level, not the book level.

<img width="161" alt="Screenshot 2024-08-07 at 7 11 37 PM" src="https://github.com/user-attachments/assets/830356b1-212d-4813-8702-fc908780e22d">

**Comment by cmurtagh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pressbooks-Product-Backlog-60ae7d807f6e370010b3d5be/issues/pressbooks/pressbooks-multi-institution/198?planning-poker) with Zenhub @arzola @fdalcin @ho-man-chan @richard015ar @tw77

**Comment by tw77** [comment]
Works as expected on dev
