### ISSUE TITLE
Refine institutions form behaviour

### ISSUE THREAD

**Issue by arzola** [pressbooks/pressbooks-multi-institution#31]
Currently the new institutions form works based on the initial features we had available. We should refine its behaviour so it reflects specific behaviours when assigning institutional managers.

Here's a list of behaviours that should be implemented:

- [x] In the institutional managers combo box, display only 'regular users' on the network. Super admins, network managers, and institutional managers already assigned to other institutions shouldn't be available for selection
![image](https://github.com/pressbooks/pressbooks-multi-institution/assets/4997549/6d138256-5952-4312-b875-2962612ac5d1)

- [x] If selecting a user that is assigned as a regular user in a different institution, that user should be assigned to the new institution and unassigned in the current one

- [x] Establish input validation for email domains to permit only letters, numbers, dashes, and `.`  I think we should also either ignore case or convert case to lowercase upon saving user input?

**Definition of done**

When creating/updating an institution the form handles the above mentioned cases as expected.

**Comment by MichelleWeremczuk** [comment]
[Figma link for error messaging](https://www.figma.com/file/ctFGUz0nF4cJb016vVg5qA/Chart-Interfaces?type=design&node-id=805%3A2546&mode=design&t=pHx0hT2jW3sGVOhD-1)

**Comment by SteelWagstaff** [comment]
Tested by adding three new institutional managers for a new institution: Fake University. Removed one of these users from the institutional manager list to see what would happen. This user `jamieholmes` no longer appears in the Assign Users list or the Network Users list, though they can still be added to the IM list. Not sure what happened to them?
![Screenshot from 2024-03-20 09-43-37](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/01851316-4353-4ad7-889f-8c815d57f168)
![Screenshot from 2024-03-20 09-43-21](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/dbd1dd50-3a83-4fbc-8a4b-bcab8a736406)
![Screenshot from 2024-03-20 09-43-09](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/88571b67-01d0-4602-8245-eda99bd28746)

**Comment by SteelWagstaff** [comment]
Nevermind -- I think I found what's happening -- this user's username was updated in the database:
![Screenshot from 2024-03-20 09-45-35](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/2179a769-8286-4787-a93a-5a5f089f7e02)

I don't know how to make the multiselect display the updated username.

**Comment by SteelWagstaff** [comment]
I was able to trigger the validation error for three cases where the string didn't match our validation rules, but the error message provided doesn't explain why these strings produce the error:
![Screenshot from 2024-03-20 09-55-19](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/b9f23b47-03a3-4cc8-843a-67ad0b8ea16b)

We might need to revise the prompt to say something like `Valid email domains can only include letters (a-z), numbers, periods, and dashes. They must include at least one period, which cannot come at the beginning or end of the domain. A period or dash must be followed by one or more letter or number.`

**Comment by SteelWagstaff** [comment]
Tested the first improvement. The only users who appear in the IM list are regular users who are not assigned as institutional managers in another institution. That works as expected.

**Comment by SteelWagstaff** [comment]
When a user who is already assigned to an institution is made an institutional manager in another institution, their institutional association is updated as expected. When removed as an institutional manager, their institutional association is unaffected. The second change works as expected as well.

**Comment by SteelWagstaff** [comment]
Tested and working as expected on dev.pressbooks.network
