### ISSUE TITLE
Build institutional manager dashboard(s)

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-multi-institution#39]
As an institutional manager, I should see a dashboard with information specific to my institution after logging into to Pressbooks. See https://www.figma.com/file/hAvkPJpDgJDDyh8g358AqR/PB-Site-Adjustments?type=design&node-id=32-9467&mode=design&t=MCrLdVEuEnZGwGWb-0.

![Screenshot from 2024-02-14 07-04-37](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/b76fa477-68be-40e7-b1d5-91b1dbb2efb3)

The topmost and bottom most blocks in the dashboard should be identical to those currently displayed to super admins/network managers. The middle sections are different. The left most block should have the heading 'Institutional Usage' and should display the institution's name and the number of books & users assigned to that institution. The 'Explore stats' button should link to the stats page _for that institution_. The 'Administer Institution' section should include links to the book and user list pages _for that institution_. 

DoD:
1. When an institutional manager logs in to a Pressbooks network, they're automatically routed to the correct institutional dashboard for their user
2. The institutional dashboard includes correct links (or link placeholders) for the stats page, book list, and user list _for their institution_
3. Institutional managers cannot load the network dashboard or an institutional dashboard for other institutions by accident

## Notes
My idea was that every institution would have their own dashboard page (each one would have an institution ID parameter in the URL). Institutional managers would get routed to the relevant institution dashboard when logging in. Super admins and network managers could view these pages by entering the URL directly and would see the same thing that the institutional managers sees.

**Comment by ho-man-chan** [comment]
Update:
- Updated my local environment to use the latest pressbooks-multi-institution plugin in the roles PR along with its dependencies.
- Reviewing existing source code relating to this task.
- Collaborating with Os for the viewing of the dashboard.

**Comment by ho-man-chan** [comment]
Update:
- Add institutional relevant data to the dashboard.
- Still needs
    - CSS for centering text, button, and make button smaller.
    - Additional testing
- Asking in Slack if we want the option to switch between institutions for admins.

**Comment by ho-man-chan** [comment]
Update:
- Add inline style and class for the stats panel. I want to meet with the devs to see what is the best method as it might be a one-off.
- Scaffold test with basic checks. I wish to add more checks: by adding users and books to an institution and redirecting properly when logging into the admin dashboard depending on the user role. 

Question to PM @SteelWagstaff :
- Do we want the option to switch between institutions for admins?

<img width="1645" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9BQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81d056e639887ff0676b05d9affdc44d8d58eaea/image.png" alt="image.png" />

**Comment by ho-man-chan** [comment]
Update:
- Updated the manager dashboard with the new design given by Steel and Michelle
- Created test using mock hooks to pass data to ui.
- Initial PR ready for review https://github.com/pressbooks/pressbooks-multi-institution/pull/57
<img width="1441" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVdNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8022c36b3335e4583abd6da370bdad3cb5085a8/image.png" alt="image.png" />

Question: Should regular non admin users see this page? At the moment, these users will not have access the the 'administrator institutions' page but sent to 'my books' page.

**Comment by SteelWagstaff** [comment]
Nope -- 'regular' non-admin users should see the standard Create a book / Clone a book dashboard.

**Comment by ho-man-chan** [comment]
Update:
1. @arzola mentioned that the PR is currently merged with the institutional-role PR and is pending final review.

**Comment by MichelleWeremczuk** [comment]
I noticed that the support resources displayed for Institutional Managers is still:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3FaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a040a8d60f4717a2dc478ea38bbaba69cf5360ca/Screenshot%202024-02-28%20at%209.22.06%E2%80%AFAM.png" alt="Screenshot 2024-02-28 at 9.22.06 AM.png" />

when it should be changed to this:
<img width="1254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM21aQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed1dda9aeaf05a2c74822b138538c140db99e910/Screenshot%20from%202024-02-22%2015-42-57.png" alt="Screenshot from 2024-02-22 15-42-57.png" />

**Comment by tw77** [comment]
Everything is working on dev except the point Michelle made above still stands: we're still seeing the Support Resources that are used in a book dashboard instead of the ones specified in this ticket.

**Comment by ho-man-chan** [comment]
Update:
- Corrected the support resources contents

**Comment by ho-man-chan** [comment]
Update:
- made the support resource block in pressbooks/pressbooks in its own blade file and this plugin is now using it in the blade, so no code duplication.

**Comment by tw77** [comment]
Working as expected as an IM on dev.

**Comment by tw77** [comment]
Re-opening because this is understood to be blocked by the issue discovered and filed here: https://github.com/pressbooks/pressbooks-multi-institution/issues/84 . When that is resolved, this can be closed because everything else is working here.

**Comment by tw77** [comment]
https://github.com/pressbooks/pressbooks-multi-institution/issues/84 is resolved (tested on dev) so this is ready to close.
