### ISSUE TITLE
Build institutional book lists (when pressbooks network analytics is active)

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-multi-institution#40]
As an institutional manager, I should see a book list with information specific to my institution after logging into to Pressbooks. See https://www.figma.com/file/hAvkPJpDgJDDyh8g358AqR/PB-Site-Adjustments?type=design&node-id=15-2447&mode=design&t=z2fac24aKvMfKhze-0

![Screenshot from 2024-02-14 07-12-45](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/4429e04e-48ca-46be-aae8-c7c438e85c86)

The text at the top of the book list should be specific to the particular institution. Only books which are assigned to the institution should be displayed in the list and available to the search/filter tools provided by this page. 

DoD:
1. The default book list should have a new 'institution' column that displays when this plugin is active for all users
2. We need to add institution filters for super admins/network managers
3. When an institutional manager loads the book list, they should see the custom version of the list with relevant information only for _their institution_
4. Institutional managers should be able to the search, filter, and download CSV features of the existing book list without special restrictions. These actions should only affect books in their book list.
5. Institutional managers should not be able to see the network book list or the book list for other institutions that they don't have access to.

Os notes -- we will need to hook into our data collector to update and centralize the institutional ID value for books in the table that the pressbooks-network-analytics plugin reads from.

## Notes
My idea was that every institution would have their own book list page (each one would have an institution ID parameter in the URL). Institutional managers would get routed to the relevant institutional book list when clicking the link from their dashboard or nav menu. Super admins and network managers could view these pages by entering the URL directly and would see the same thing that the institutional managers sees.

**Comment by tw77** [comment]
Everything here works as expected on dev.
