### ISSUE TITLE
Properly manage institutional managers' capabilities

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-multi-institution#45]
As an institutional manager, I need to be able to do the following:
## Institutional Dashboard
- [x] View my institutional dashboard (I should not be able to access any other institutions' dashboard, or the general network dashboard)

## Book List
- [x] View and interact with a book list which contains only those books assigned to my institution

From the book list, I need to be able to do the following
- [ ] Access the book dashboard and behave as a book administrator for all books which belong to my institution (I should not be allowed to access the dashboard or administer books which do not belong to my institution)
- [x] Deactivate and delete any book which belongs to my institution (I should not be allowed to deactivate or delete any books which do not belong to my institution, unless I'm explicitly enrolled as a book admin in the book, in which case, the normal delete book capabilities should pertain)
- [ ] I should **NOT** be able to see or access the site info page for any books on the network, even those which belong to my institution) (i.e. `wp-admin/network/site-info.php?id=3`). Ideally we would remove the `Edit` link beneath the book title in their book list (both in pressbooks-network-analytics and the default book list, if possible). 

## User List
- [x] View and interact with a user list which contains only those users assigned to my institution

From the user list, I need to be able to do the following:
- [x] View the user info page for all users which belong to my institution (I should not be allowed to access this page for users which do not belong to my institution) `wp-admin/network/admin.php?page=pb_network_analytics_userlist&id=1`
- [x] Edit user profile & account details for all users which belong to my institution (I should not be allowed to access the user profile page for users which do not belong to my institution) `wp-admin/network/user-edit.php?user_id=1`
- [x] Delete any user which belongs to my institution (I should not be allowed to delete a user who does not belong to my institution)

## Stats Page
Finally, I need to be able to: 
- [x] View and interact with a stats page which only displays data from users/books assigned to my institution (yet to be built, but should resemble the current network manager stats page)

**Comment by richard015ar** [comment]
I assigned it myself to review and test the WIP Os is working on

**Comment by arzola** [comment]
I'm still working on this I've been working on book permissions (all book's menus management) and allowing users to see properly the content they have access

**Comment by MichelleWeremczuk** [comment]
On the book list for institutional managers, we had identified that an institution column would be added. It currently isn't in the chart, do we still want it?

**Comment by tw77** [comment]
As an institutional manager, I'm able to access the site info page (via the 'Edit' link in the book list or 'Edit Book' in the top nav of the book dashboard) for books that belong to my institution, i.e. `wp-admin/network/site-info.php?id=11`. According to the description in this ticket, I shouldn't have access to the site info page for any books, even books that belong to my institution.

Going from here
<img width="485" alt="Screenshot 2024-03-03 at 4 14 10 PM" src="https://github.com/pressbooks/pressbooks-multi-institution/assets/44182629/f9d13258-e6ba-4126-bfd5-2c8b289fe31e">

or here
<img width="720" alt="Screenshot 2024-03-03 at 4 12 22 PM" src="https://github.com/pressbooks/pressbooks-multi-institution/assets/44182629/f9b9439d-17fe-48d8-b887-86a4e6bbdde6">

to here shouldn't be possible
<img width="912" alt="Screenshot 2024-03-03 at 4 15 11 PM" src="https://github.com/pressbooks/pressbooks-multi-institution/assets/44182629/12d7e582-e686-4725-8d69-ccd2f8f8884e">

**Comment by tw77** [comment]
The other issue is that as an institutional manager, I'm able to access the book dashboard and act as an administrator for books on the network that don't belong to my institution. Even though these books don't appear in my book list, I can navigate to the dashboard for any of these books through the 'Admin' link in the webbook or 'Edit' button in a webbook chapter, which is available for me for any book on the network. I can also navigate to any book's Media Library through the Network Storage viewer in the Stats page, or to any book's Cloning Stats through the Most Cloned Books viewer in the Stats page, also leading to the book's dashboard. 

But otherwise, everything else is working. I have the expected capabilities and limitations with the user list.

**Comment by SteelWagstaff** [comment]
Closing in favor of #74
