### ISSUE TITLE
Gather & prioritize feedback from consortial users based on pre-release candidate

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-multi-institution#59]
We now have a release candidate that eCampus is using for the shared institutions plugin. We should share this working software with relevant clients (determined by sales), provide information and training on usage, and collect and organize their feedback and suggestions before work is 'finished' and released to all clients.

DoD:
- [x] Conversation with Sales/Marketing about the details on how/when to invite people and the data they would need
- [x] Invite all clients requested by sales to use the new plugin + provide demo recording and docs 
- [x] Develop survey instrument to gather overall feedback
- [x] Invite NMs to the staging site day-of, allow preview access until midnight 
- [x] Conduct preview sessions
- [x] Send out surveys to all participants after session
- [x] Gather and compile feedback from surveys and in-person sessions

**Comment by MichelleWeremczuk** [comment]
Draft of testing plan and more refined steps can be found [here](https://docs.google.com/document/d/12lmP22crkdQXy0LSIs4Q851kZZuE54JNhR1-f82X6x0/edit?usp=sharing)

**Comment by beckej13820** [comment]
Let me know if you need open source users as well.

**Comment by cmurtagh** [comment]
> Let me know if you need open source users as well.

Thank you. We'll be in touch!

@MichelleWeremczuk has invited some users already and this is actually in progress this sprint.

**Comment by MichelleWeremczuk** [comment]
Preview sessions have been scheduled with the following:

- Alexandra Marcaccio (atlanticoerlead@caul-cbua.ca, execdir@caul-cbua.ca) on May 7 (1PM EST)
- Etta Thornburg (etta.thornburg@mnsu.edu) on May 9 (4PM EST)
- Kristy Lacroix (lacroixk@campusmanitoba.ca, mcdougallc@campusmanitoba.ca, gordond@campusmanitoba.ca) on May 13 (3PM EST)
- Elizabeth Kelly + Emily Frank (elizabeth.kelly@laregents.edu, emily.frank@laregents.edu) on May 14 (12PM EST)
- Amy Hofer (hofera@linnbenton.edu) rescheduled for May 15 (1PM EST)

**Comment by cmurtagh** [comment]
I've added Etta Thornburg as a network administrator for today's session. Their username is 'ettathornburg' since only alphanumeric characters are allowed.

**Comment by MichelleWeremczuk** [comment]
Here's a [google doc with notes and questions](https://docs.google.com/document/d/1gvYiyhfp6YYyUfNJ_OQyp_pmwpCcnxyYSnJAaAuzzq0/edit?usp=sharing) I've been gathering from the sessions

**Comment by MichelleWeremczuk** [comment]
Final participants for today:

Jamie.holmes@tulsacc.edu, Marianne.myers@tulsacc.edu

**Comment by cmurtagh** [comment]
I've reset the DB and added them as network managers.
