### ISSUE TITLE
Implement new settings for institutions & update institution list display

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-multi-institution#61]
As a Pressbooks account manager, I need to be able to indicate whether or not an institution on a Pressbooks shared network 
1. is entitled to have institutional managers
2. has purchased premium member buy-in
3. has a specific book limit associated with their buy-in

This information should only be visible/editable by super admins (i.e. Pressbooks staff).

## Adjustments to Add/edit institution form for super admins
We should change the add/edit institution form in the following ways:
- [x] Remove the user limit field (we don't need to keep track of this for individual institutions)
- [x] Add a new setting 'Institutional Managers Allowed' [boolean, default false] -- only visible to/editable by super admins
- [x] Add a new setting 'Premium Member Buy-in' [boolean, default false]  -- only visible to/editable by super admins
- [x] Ensure that there is a 'Book Limit' setting [numeric, positive integers only, default null]  -- only visible to/editable by super admins
![Screenshot from 2024-02-27 10-25-48](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/0dfb18b1-d66a-4449-b9c4-459190fbeb8c)

## Adjustments to Add/edit institution form for network managers
- [x] Don't display any of the super-admin only fields
- [x] Make the institutional manager field read-only unless certain conditions are met (they should be able to add/remove institutional managers if a) the network itself is 'unlimited', b) the Institutional Managers Allowed setting is true, or c) Premium Member Buy-in is true)

## Adjustments to Institution List
We should change the Institution List in the following ways:
- [x] Remove user limit indicators after the user count for each institution
- [x] Add a column called 'Buy-in' that displays a check mark [box is checked if NETWORK is unlimited OR if Premium Member Buy-in is true for a given institution]
- [x] Add new new summary rows at the bottom of the table between Unassigned and All Network totals: Shared Network Totals and Premium Member Totals. Shared Network Totals should be calculated as the sum of all books/users which are unassigned or assigned to institutions which HAVE NOT purchased Premium Member Buy-In. Premium Member Totals should be calculated as the sum of all books/users which are assigned to institutions which HAVE purchased Premium Member Buy-In. 
- [x] If the network itself has a book limit, display this value after the book count in the new Shared Network Total Row
![Screenshot from 2024-02-27 09-47-03](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/a92cf7e6-4011-4f48-8d68-71d11b8d4992)

See Figma wireframe: https://www.figma.com/file/ctFGUz0nF4cJb016vVg5qA/Chart-Interfaces?type=design&node-id=665-1527&mode=design&t=ZjKimRyYfu3oNtx2-0

## Requirements
Here's what each setting should do:
- If the NETWORK itself is unlimited (see https://github.com/pressbooks/pressbooks-network-analytics/issues/335), we can ignore the settings for individual institutions. When the network itself is unlimited:
    1. Network managers should be able to create institutional managers for all institutions.
    2. The buy-in column should not be displayed in the institution list
    3. Institutions should not display a book limit in the book limit column
    4. We should not display the Premium Member Totals Row
    5. All Institutions' books and users should count towards the Shared Network Totals
    6. The Shared Network Totals row should show `/unlimited` as its book limit value. 
- If the NETWORK is NOT unlimited, and Institutional Managers Allowed and Premium Member Buy-in are both false:
    1. Network managers should not be able to create institutional managers for this institution
    2. The buy-in column should not be checked
    3. The institution should not display book/user limits after their book/user count
    4. This institution's books and users should count towards the Shared Network Totals and should NOT count towards Premium Member Totals
- If the NETWORK is NOT unlimited, Institutional Managers Allowed is true and Premium Member Buy-in is false:
    1. Network managers should be able to create institutional managers for this institution
    2. The buy-in column should not be checked
    3. The institution should not display book/user limits after their book/user count
    4. This institution's books and users should count towards the Shared Network Totals and should NOT count towards Premium Member Totals
 - If the NETWORK is NOT unlimited, Institutional Managers Allowed is true or false, Premium Member Buy-in is true, and Book Limit is empty:
    1. Network managers should be able to create institutional managers for this institution
    2. The buy-in column should be checked
    3. The institution should display `/unlimited` after their book total
    4. The institution's books and users should count towards the Premium Member Totals and should be excluded from the Shared Network Totals calculation
- If the NETWORK is NOT unlimited, Institutional Managers Allowed is true or false, Premium Member Buy-in is true, and Book Limit has a positive integer value:
    1. Network managers should be able to create institutional managers for this institution
    2. The buy-in column should be checked
    3. The institution should display `/BOOKCOUNTVALUE` after their book total
    4. The institution's books and users should count towards the Premium Member Totals and should be excluded from the Shared Network Totals calculation

Additional details/go to market planning in this document: https://docs.google.com/document/d/1K637TC99kL7Zd0mTgGiv7qDg0H4VZVMDzU_chmy5C1Y/edit?usp=sharing

## Conditional logic
1. Super admins should always be able to add/remove institutional managers
2. Network managers should be able to add/remove institutional managers if a) the network itself is 'unlimited', b) the Institutional Managers Allowed setting is true, or c) Premium Member Buy-in is true.

**Comment by fdalcin** [comment]
Was not able to set the **Institutional Managers** field as read only for now. There seems to be a limitation with https://github.com/greatislander/pressbooks-multiselect component and `disabled` attribute.

**Comment by SteelWagstaff** [comment]
Michelle and I did preliminary testing on dalcindev. Everything we tested was working as expected.

**Comment by tw77** [comment]
Works as expected on dev.pressbooks.network following the requirements here.
