### ISSUE TITLE
Styling/layout improvements

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-multi-institution#73]
We have a series of desired layout and styling improvements we'd like to see implemented before release: https://docs.google.com/document/d/1xFp1yAdHqC2NIyF4TxMWCMjYWJJQFAqndyGY0c6I1rI/edit

## Nav Menu
- [x] place new `Institutions` option directly below `Users` for super admins & network managers. if not possible, put above `Books`
## Institutions list
- [x] default display 50 items per page
- [x] reduce size of Institution name to match other text
- [x] change ‘Unassigned’ and ‘Total Items’ to same font size & weight as Institution names
- [x] reduce width of books/users columns (extra space spread across remaining columns)
- [x] improve contrast between text & background color and add clearer separator between calculated rows at bottom (‘unassigned’ + ‘total items’) (#C3C4C7)
- [ ] book usage number should link to institution’s book list [skip for now]
- [ ] user usage number should link to institution’s user list [skip for now]
## Add Institutions page
- [x] make sure input fields are top aligned with prompt text
## Assign users
- [x] don’t bold user’s name
- [x] default display 50 items per page
- [x] link username to (edit) user profile 
## Assign books
- [x] default display 50 items per page
- [x] apply border bottom to all table cells
- [x] Book titles shouldn't be wrapped in `<p>` elements
- [x] book URL should link to book dashboard rather than homepage (add /wp-admin)
- [ ] reduce width of institution column to 300px (extra space can go to title / book admin) 
## Book/user list
- [x] Only display institutions in the filter if there are books/users which have that institution assigned (match behaviour of other filters)
- [x] Display `Unassigned` as the institution value in the book list when books are not assigned to any institution
- [x] Remove `institution_id` column from book list CSV downloads

**Comment by MichelleWeremczuk** [comment]
There is a very small inconsistency regarding the line weight in the header and footer rows of the assign books and assign users tables:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3JaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29fae801e7644df03af753a0d76526b52b52f493/Screenshot%202024-03-13%20at%209.59.13%E2%80%AFAM.png" alt="Screenshot 2024-03-13 at 9.59.13 AM.png" />

**Comment by tw77** [comment]
Testing on dev.pressbooks.network

Institutions does not appear directly below Users right now. It's currently showing up below Appearance

<img width="150" alt="Screenshot 2024-03-14 at 9 10 49 AM" src="https://github.com/pressbooks/pressbooks-multi-institution/assets/44182629/069b0e64-d43f-4d06-8030-77844c69f4d6">

**Comment by SteelWagstaff** [comment]
One strange thing I'm noticing:
in the assign users table, some user names have `class="row-title"` added to the div containing the value. This causes the text to appear at 14px with 600 weight. I don't think these elements should have the row-title class applied. 
![Screenshot from 2024-03-14 09-11-16](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/2fe4bd63-df96-42db-be0f-65fe007f2916)

**Comment by tw77** [comment]
The menu order issue I saw is fixed with the deploy to dev this minute.

**Comment by SteelWagstaff** [comment]
We can also reduce the width of the new 'buy-in' column to ~65px. 
![Screenshot from 2024-03-14 09-38-41](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/fb618f04-3c98-40dc-a803-cc66b94b0e53)

**Comment by SteelWagstaff** [comment]
Contrast within table row text is sufficient for AA (4.5:1) but not AAA (7:1). One idea would be to use same background and foreground color as used in the admin bar at left. 

Background: #dedede
Text color: #333 

Appearance with proposed changes applied: 
![Screenshot from 2024-03-14 09-47-41](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/c0478555-35fd-4e95-a242-410f705b0755)

Current:
![Screenshot from 2024-03-14 09-48-31](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/c698f6af-e164-4e84-bdda-4d5a1728c69d)
After:
![Screenshot from 2024-03-14 09-48-02](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/c24b28f1-23a3-4ae4-9e33-aa0cde237ec3)

**Comment by SteelWagstaff** [comment]
All proposed changes have been tested on dev.pressbooks.network. The three items we didn't address in this ticket were:
- [ ] book usage number should link to institution’s book list 
- [ ] user usage number should link to institution’s user list
- [ ] reduce width of institution column to 300px (extra space can go to title / book admin)

A future task should probably be to develop and implement a better responsive grid layout for the institution list, assign books, and assign users tables. Column widths that are percentage based with min values seems like a promising approach?
