### ISSUE TITLE
Improve permission management for institutional manager role

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks-multi-institution#74]
As an institutional manager, I should NOT be able to see or access the site info page for any books on the network, even those which belong to my institution) (i.e. wp-admin/network/site-info.php?id=3). Ideally we would remove the Edit link beneath the book title in their book list (both in pressbooks-network-analytics and the default book list, if possible).

As an institutional manager, I should NOT be able to access the admin dashboard of books that do not belong to my institution (unless I have been added to the book with a specific role), even when I provide the URL directly.

See https://github.com/pressbooks/pressbooks-multi-institution/issues/45#issuecomment-1975419607 and https://github.com/pressbooks/pressbooks-multi-institution/issues/45#issuecomment-1975466487

**Comment by tw77** [comment]
This is working as expected on dev, but can only be closed as done once the issue discovered and filed at https://github.com/pressbooks/pressbooks-multi-institution/issues/84 is resolved.

**Comment by tw77** [comment]
https://github.com/pressbooks/pressbooks-multi-institution/issues/84 is resolved (tested on dev) so this is ready to close.
