### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks-multi-institution#76]
As a Developer I'd like to improve our current source code applying the following changes:
- [x] Users list: when adding institution data, we can hook the users' query instead of appending it separately. For reference, check book list approach, which does it.
- [x] Split PermissionsManager class and move pieces into the proper places and add more tests
- [x] https://github.com/pressbooks/pressbooks-network-analytics/pull/331#discussion_r1507733117
- [x] Increase test coverage adding more cases for [https://github.com/pressbooks/pressbooks-multi-institution/blob/f48fbe5cb4d1eb62da931703e8512665ee7938be/tests/Feature/Support/BookListTest.php#[…]9](https://github.com/pressbooks/pressbooks-multi-institution/blob/f48fbe5cb4d1eb62da931703e8512665ee7938be/tests/Feature/Support/BookListTest.php#L139-L179)

DoD: Implement necessary changes to address the issues mentioned above.

**Comment by arzola** [comment]
* I extracted some booklist functionality to share it with a new userlist class to append institutions behaviour, working more on that and today I'll start working on refactoring the PermissionsManager class

**Comment by tw77** [comment]
@arzola @richard015ar As a regular user on oscardev.pressbooks.network (thomtestuser) I'm able to view https://oscardev.pressbooks.network/wp/wp-admin/network/admin.php?page=pb_network_page
 
<img width="1412" alt="Screenshot 2024-03-27 at 1 15 56 PM" src="https://github.com/pressbooks/pressbooks-multi-institution/assets/44182629/e3d7fbd3-b7f3-41f3-9307-d3051611aafa">



This user was a super admin before but then I changed them to a regular user. I've tried logging in and out as this user and it still shows me the network dashboard.

**Comment by tw77** [comment]
This issue does not happen with a new regular user that I just added to the network, though.

**Comment by arzola** [comment]
Interesting Let me see this, thanks for testing @tw77

**Comment by tw77** [comment]
Tested on dev on Thursday, which lead to the team finding and filing https://github.com/pressbooks/pressbooks-multi-institution/issues/131. Do we close this ticket in favour of that one?
