### ISSUE TITLE
Absent users in analytics users page and unassigned filter

### ISSUE THREAD

**Issue by richard015ar** [pressbooks/pressbooks-multi-institution#90]
As a super admin, when we remove users from Root Site it seems to remove the users from the PB Analytics users list causing some inconsistencies between the total users and the one displayed.

On the other hand, the Unassigned filter in the PB Users list does not work as expected. When you apply the `unassigned` institution filter as a super admin, and you don't have any institution created, it does show an empty user list.

**Comment by tw77** [comment]
Fixed and working as expected on dev.pressbooks.network.
